FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

# Build the React app for production (you may need to adjust this command)
RUN npm run build

# Serve the built production files using serve (an alternative to npm start)
RUN npm install -g serve

# Specify the command to serve the built application
CMD ["serve", "-s", "build"]