name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment and Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build it
        run: npm run build

      - name: Verify build directory contents
        run: |
          ls -la ./build
          if [ ! -d ./build ] || [ -z "$(ls -A ./build)" ]; then
            echo "Build directory is empty or does not exist."
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./build

  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./build

      - name: Build Docker image with Dockerfile.prod
        run: docker build -t dockerdemo-i -f Dockerfile.prod .

  deploy-react-for-github-pages:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./build
