name: Docker Build and Run

on:
  push:
    branches:
      - main  # When code is pushed to the branch called 'main', the following jobs will be executed.

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a maximum execution time for the job

    steps:
      - name: Check current directory and list contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the directory:"
          ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image with Dockerfile.prod
        run: docker build -t dockerdemo-i -f Dockerfile.prod .

      # Removing this for now as the process never ends and therefore the action never completes, and neither does the build.
      # I will return to this later, when I have more information.
      # - name: Run Docker container
      #   run: docker run dockerdemo-i

  build-and-deploy-react-for-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./build